In [2]:
import copy, math
import numpy as np
import matplotlib.pyplot as plt
np.set_printoptions(precision=2)

In [3]:
X_train = np.array([[2104,5,1,45], [1416,3,2,40], [852,2,1,35]])
y_train = np.array([460, 232, 178])

In [4]:
X_train.shape

(3, 4)

In [5]:
type(X_train)

numpy.ndarray

In [6]:
X_train

array([[2104,    5,    1,   45],
       [1416,    3,    2,   40],
       [ 852,    2,    1,   35]])

In [7]:
y_train.shape

(3,)

In [8]:
type(y_train)

numpy.ndarray

In [9]:
y_train

array([460, 232, 178])

In [10]:
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])

In [11]:
w_init.shape

(4,)

In [12]:
type(b_init)

float

In [16]:
def predict(x, w, b):
    p = np.dot(w,x) + b
    return p

In [17]:
x_vec = X_train[0,:]
x_vec

array([2104,    5,    1,   45])

In [20]:
f_wb = predict(x_vec, w_init, b_init)
f_wb

459.9999976194083